### ISSUE TITLE
Handle the case where a tracked file is not found

### ISSUE THREAD

**Issue by hargup** [felvin-search/gpt-repository-loader#12]
Error:
```
gpt-repository-loader -c .
Traceback (most recent call last):
  File "/Users/harshwork/opt/anaconda3/bin/gpt-repository-loader", line 33, in <module>
    sys.exit(load_entry_point('gpt-repository-loader', 'console_scripts', 'gpt-repository-loader')())
  File "/Users/harshwork/code/gpt-repository-loader/gpt_repository_loader/gpt_repository_loader.py", line 87, in main
    repo_as_text = git_repo_to_text(args.repo_path, args.preamble)
  File "/Users/harshwork/code/gpt-repository-loader/gpt_repository_loader/gpt_repository_loader.py", line 74, in git_repo_to_text
    process_repository(repo_path, ignore_list, output_stream)
  File "/Users/harshwork/code/gpt-repository-loader/gpt_repository_loader/gpt_repository_loader.py", line 54, in process_repository
    with open(full_path, 'r', errors='ignore') as file:
FileNotFoundError: [Errno 2] No such file or directory: './packages/prisma/.env'
```

**Comment by hargup** [comment]
Good issue to try out aider

**Comment by hargup** [comment]
Fixed with aider. Aider handled this with grace and charm.
